### ISSUE TITLE
Full of UnexpectedMetric

### ISSUE THREAD

**Issue by ivandal77** [douban/Kenshin#16]
Dear,
collectiong metric from netdata I obtian a lot of 
` UnexpectedMetric:`
fron cache.
How solve and what is causing this? If I collect in other installation it works fine.
Here is my configuration file:
`[cache]
CONF_DIR        = /data/kenshin/Kenshin/conf
LOCAL_DATA_DIR  = /data/kenshin/Kenshin/storage/data
LOCAL_LINK_DIR  = /data/kenshin/Kenshin/storage/link
LOG_DIR         = /data/kenshin/Kenshin/storage/log
PID_DIR         = /data/kenshin/Kenshin/storage/run

LINE_RECEIVER_INTERFACE = 0.0.0.0
PICKLE_RECEIVER_INTERFACE = 0.0.0.0
CACHE_QUERY_INTERFACE = 0.0.0.0

LOG_UPDATES = True
MAX_CREATES_PER_MINUTE = 5000000
NUM_ALL_INSTANCE = 2

DEFAULT_WAIT_TIME = 1

[cache:0]
LINE_RECEIVER_PORT = 2003
PICKLE_RECEIVER_PORT = 2004
CACHE_QUERY_PORT = 7002

[cache:1]
LINE_RECEIVER_PORT = 2013
PICKLE_RECEIVER_PORT = 2014
CACHE_QUERY_PORT = 7012
`
thanks,

Ivan

**Comment by zzl0** [comment]
## Root cause of `UnexpectedMetric` 

``` Python
instance = get_instance_of_metric(metric, settings['NUM_ALL_INSTANCE'])
if (instance != int(settings['instance']) and
    not metric.startswith(settings.RUROUNI_METRIC)):  ## you can ignore this line now
  log.cache("UnexpectedMetric: %s" % metric) 
  instrumentation.incr('droppedCreates')
  raise UnexpectedMetric()
```

The root cause is `instance != int(settings['instance']`, which means:

1. You sent metrics to Kenshin-cache directly. or
2. The `cache instance` configuration in [rurouni.conf](https://github.com/douban/Kenshin/blob/master/conf/rurouni.conf.example) doesn't match the configuration in [relay.conf](https://github.com/douban/graphite-kenshin/blob/master/conf/relay.conf)


## How to fix

1. You should send all of your metrics to `carbon-c-relay`.
2. The `cache instance` configuration in rurouni.conf should match the configuration in relay.conf.

```
            rurouni.conf                         relay.conf                       explanation

[cache:0]
LINE_RECEIVER_PORT = 2003         <---->       127.0.0.1:2003=0        line port(2003), instance number(0)
PICKLE_RECEIVER_PORT = 2004
CACHE_QUERY_PORT = 7002

[cache:1]
LINE_RECEIVER_PORT = 2013         <---->       127.0.0.1:2013=1        line port(2013), instance number(1)
PICKLE_RECEIVER_PORT = 2014
CACHE_QUERY_PORT = 7012
```

## Why do we need the instance number verification logic

We know that people make mistakes -- we are fallible (e.g wrong configuration).

**Comment by ivandal77** [comment]
Dear,
sorry but I don't understand.
Why I have to send all metric to carbon-c-relay. I cannot send directly to Kenshin-cache? 
Thanks for your support and patience

**Comment by zzl0** [comment]
Relay is for replication and sharding. Please read [carbon-c-realy](https://github.com/douban/carbon-c-relay) or google for `graphite cluster`.
