### ISSUE TITLE
is there any special setting for Graphite-Web and Grafana3?

### ISSUE THREAD

**Issue by rmrf** [douban/Kenshin#7]
After change from Carbon Whisper to Kenshin for collecting metrics, Grahpite-web can't explore the metrics any more, from the graphite-web left tree view, folder architecture is explorable, but there is no metrics inside (*.hs soft link are there on the filesystem, but from graphite-web view the metrics are missing). it can't recognize the *.sh file extension?

Grafana3 can't see the metrics neither. 

is there any special setting for Graphite-Web and Grafana3

**Comment by zzl0** [comment]
Thanks for your interest in Kenshin.

Yes, the offical Graphite-Web don't support Kenshin file format now, we have changed the graphite-web source code for internal use (https://github.com/douban/Kenshin/issues/4). We didn't open source it, because it has some internal dependency (internal fnv1a hash).

We will write a plugin for using graphite-web (and/or graphite-api) with Kenshin-based storage backend.

**Comment by rmrf** [comment]
OK, Thanks @zzl0 ， it will be great  put this kind of information inside the project README file or design document :)
